"""
Django settings for todoproject project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-z$b79#92qugc_1#b-u-bhf=go6e6glo7$-tk4!+!zig3p8a1r7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    ".onrender.com",
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin', #admin panel
    'django.contrib.auth', #login logout users permissions
    'django.contrib.contenttypes',
    'django.contrib.sessions', #User login hone ke baad session maintain karta hai.
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'tasks',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'todoproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request', #{{ request.user }} in templates
                'django.contrib.auth.context_processors.auth',#{% if user.is_authenticated %} in templates
                'django.contrib.messages.context_processors.messages', #Ye messages framework ko templates me available karata hai.
                #Agar ye context processor hata diya, to template me messages variable hi nahi milega.
            ],
        },
    },
]

WSGI_APPLICATION = 'todoproject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,#Lekin conn_max_age=600 se Django kuch time tak same connection reuse karta hai, jisse performance improve hoti hai.
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',#Password username se bahut similar hai.
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',#Password minimum length se chhota hai.
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',#12345678 Ye bahut common passwords hain.
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',#Agar password sirf numbers ho:12345 to reject
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = "Asia/Kolkata"

USE_I18N = True #Internationalization Ye Django ko multiple languages support karne me help karta hai.

USE_TZ = True 


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

LOGIN_URL = "login" 

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage" 